
name: Deprovision Participant

on:
    workflow_dispatch:

jobs:
  delete-resource-groups:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read GitHub handles from file
        id: read-handles
        run: |
          echo "::set-output name=handles::$(cat provisioning/cleanup-handles.txt)"

